### ISSUE TITLE
(Automatically) update GitHub releases

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#148]
Latest release is 0.3.2 (although yet not available on [Maven Central](https://repo1.maven.org/maven2/org/junit-pioneer/junit-pioneer/)), but according to the [releases page](https://github.com/junit-pioneer/junit-pioneer/releases), it is 0.1.2.

I assume this is because nobody published the existing tags as actual releases on GitHub—as this gets easily forgotten.

However, one can automate this with [Travis' release provider for GitHub](https://docs.travis-ci.com/user/deployment/releases/):

```yaml
- provider: releases
  api_key: "${GH_TOKEN}"
  on:
    branch: master
    jdk: openjdk8
```

If you want to, I can submit a PR for this, but one of you guys has to provide a Github OAuth token as an environment variable (e.g. `GH_TOKEN` as above) in Travis.
