### ISSUE TITLE
Website refers to old release version

### ISSUE THREAD

**Issue by rweisleder** [junit-pioneer/junit-pioneer#497]
The homepage https://junit-pioneer.org/ currently refers to version 1.3.0 as the current release while 1.4.2 is the newest available in Maven Central.

Looks like some automation is not working properly.

**Comment by beatngu13** [comment]
Hi @rweisleder,

Thanks for raising this issue. The problem is that our (outdated) [website build](https://github.com/junit-pioneer/junit-pioneer.github.io/blob/grandmaster/build.gradle#L118) still expects a `version.properties` file, which has been removed as part of #475.

@nipafx @aepfli I believe we can quite easily fix that by using the `client-payload` input from [`peter-evans/repository-dispatch`](https://github.com/peter-evans/repository-dispatch), the action we currently use to trigger the website build after a Pioneer release.

In order to do so, I would adapt the ["Trigger website build" step](https://github.com/junit-pioneer/junit-pioneer/blob/main/.github/workflows/release-build.yml#L46) in this repo as follows:

```yml
- name: Trigger website build
   uses: peter-evans/repository-dispatch@v1
   with:
     token: ${{ secrets.GH_WRITE_TOKEN }}
     repository: junit-pioneer/junit-pioneer.github.io
     event-type: triggerSiteBuild
     # we already define the release version as a workflow input
     client-payload: '{"pioneer-release-version": "${{ github.event.inputs.version }}"}'
```

The [website workflow](https://github.com/junit-pioneer/junit-pioneer.github.io/blob/grandmaster/.github/workflows/actions.yml#L31) then can pass it to the Gradle build:

```yml
- name: Gradle setup, build and push
   uses: eskatos/gradle-command-action@v1
   with:
     arguments: >
       setup buildSite pushSite
       --no-daemon --stacktrace
       -Ppioneer-release-version=${{ github.event.client_payload.pioneer-release-version }}
```

What do you think?
